server:
  port: ${PORT:8080}
  
management:
  security:
    enabled: false

spring:
  application:
    name: awesome-media-frontend    
  thymeleaf:
    prefix: classpath:/static/html/
                
api:
  bff:
    path: /
  services:
    url: http://localhost:8090
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000    
            
