server:
  port: 8090

management:
  security:
    enabled: false    

promotion: action
name :jisang-edited

spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:memdiadb;
    username: sa
    password: null
  h2:
    console:
      enabled: true
